[project]
org-name = "ballerina"
version = "@toml.version@"

[platform]
target = "java11"

    [[platform.libraries]]
    artifactId = "runtime"
    version = "@project.version@"
    path = "../runtime-native/build/libs/runtime-native-@project.version@.jar"
    groupId = "ballerina"
    modules = ["runtime"]
