[package]
org = "ballerina"
name = "runtime"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../runtime-native/build/libs/runtime-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "runtime"
version = "@project.version@"
